### PR TITLE
Should export `css` and `injectGlobal`

### PR DESCRIPTION
**Pull request by u3u**

### CODE REVIEW

**Comment by egoist** [comment]
Maybe export everything from emotion, since react-emotion did https://github.com/emotion-js/emotion/blob/master/packages/react-emotion/src/index.js#L8

**Comment by u3u** [comment]
Updated

**Comment by u3u** [comment]
https://github.com/egoist/vue-emotion/blob/e0ec437b27ce437be5a56db1ab1d0b9e95a8910e/src/index.js#L10-L12

Inadvertently formatted causes xo-lint check to fail 😅

**Comment by egoist** [comment]
it's weird circleci isn't enabled for pull request 😅

**Pull request merged**
